// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/[name].tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/about.tsx";
import * as $3 from "./routes/api/joke.ts";
import * as $4 from "./routes/chart.tsx";
import * as $5 from "./routes/games/[week].tsx";
import * as $6 from "./routes/github/[username].tsx";
import * as $7 from "./routes/index.tsx";
import * as $8 from "./routes/probs/[gameId].tsx";
import * as $$0 from "./islands/Counter.tsx";
import * as $$1 from "./islands/GameList.tsx";
import * as $$2 from "./islands/ProductDetails.tsx";

const manifest = {
  routes: {
    "./routes/[name].tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/about.tsx": $2,
    "./routes/api/joke.ts": $3,
    "./routes/chart.tsx": $4,
    "./routes/games/[week].tsx": $5,
    "./routes/github/[username].tsx": $6,
    "./routes/index.tsx": $7,
    "./routes/probs/[gameId].tsx": $8,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
    "./islands/GameList.tsx": $$1,
    "./islands/ProductDetails.tsx": $$2,
  },
  baseUrl: import.meta.url,
};

export default manifest;
