name: Deploy
on: [push]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: rc

      - name: Run linter
        run: deno lint

      - name: Run tests
        run: deno test -A --unstable

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "rewatchable-games"
          entrypoint: "./main.ts" # TODO: update entrypoint
