name: lhci check
on: [deployment]

jobs:
  check:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
    - name: Lighthouse CI Action
      # You may pin to the exact commit or the version.
      # uses: treosh/lighthouse-ci-action@e0fe113967eee84b631d526ed18ce001f35fe9e9
      uses: treosh/lighthouse-ci-action@v9
      with:
        # Address of a LHCI server
        serverBaseUrl: https://rewatchable-games.deno.dev/
        # API token to push to LHCI server
